homeassistant:
  name: Home
  latitude: 47.7396
  longitude: -122.3426
  elevation: 129
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize:
    climate.thermostat_heating_1_9_1:      { friendly_name: Thermostat }
    climate.thermostat_cooling_1_9_2:      { hidden: true }
    climate.thermostat_heating_econ_9_11:  { hidden: true }
    climate.thermostat_cooling_econ_9_12:  { hidden: true }
    sensor.frontdoorlock_alarm_type_16_0:  { hidden: true }
    sensor.frontdoorlock_alarm_level_16_1: { hidden: true }
    sensor.backdoorlock_alarm_type_17_0:   { hidden: true }
    sensor.backdoorlock_alarm_level_17_1:  { hidden: true }

logger:
  default: info
  logs:
    homeassistant.core: warning
    homeassistant.components.sensor.command_line: warning
    custom_components: debug
    custom_components.bwio: info

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  #ssl_peer_authority: !secret ssl_peer_authority

frontend:
conversation:
history:
logbook:
sun:
recorder: { purge_days: 14 }

zwave:
  usb_path: /dev/zwave
  config_path: /home/pi/.homeassistant/ozwconfig
  polling_interval: 60000
  customize:
    binary_sensor.multisensor_sensor_18_0:     { ignored: true }
    sensor.multisensor_temperature_18_1:       { ignored: true }
    sensor.multisensor_luminance_18_3:         { ignored: true }
    sensor.multisensor_relative_humidity_18_5: { ignored: true }
    sensor.thermostat_temperature_9_1: { polling_intensity: 1 }
    climate.thermostat_heating_1_9_1:  { polling_intensity: 1 }

bwio:
  port: /dev/bwio

usercode:
locklogger:

panel_custom:
  - name: locks
    sidebar_title: ZWave Locks
    sidebar_icon: mdi:lock

sensor:
  - platform: systemmonitor
    resources:
      - { type: memory_use_percent }
      - { type: processor_use }
  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'

binary_sensor:
  - platform: bwio
    pins: 
       0:  [ littlewindow,     opening ]
       1:  [ diningwindow,     opening ]
       2:  [ pin2,             opening ] # unknown signal, always ok, where is it?
       3:  [ primarymotion,    motion  ]
       # 4: disconnected wire in the wall of the bedroom
       # 5: no input present
       # 6: no input present
       # 7: isn't connected, used as ground
       8:  [ livingroomwindow, opening ]
       9:  [ officewindow,     opening ]
       10: [ backdoor,         opening ]
       11: [ bedroomslider,    opening ]
       12: [ garagedoor,       opening ]
       13: [ patioslider,      opening ]
       14: [ frontdoor,        opening ]
       # 15 isn't connected, used as ground

switch:
  - platform: bwio
    pins: 
      11: garagedoor
      15: alarm

script:
  garage_door:
    sequence:
      - service: switch.turn_on
        data: { entity_id: switch.garagedoor }
      - delay:
          milliseconds: 10
      - service: switch.turn_off
        data: { entity_id: switch.garagedoor }

shell_command:
  cleantemps: './cleantemps.py'

group: !include groups.yaml
automation: !include automation.yaml

