# Core components and setup
homeassistant:
  name: Home
  latitude: 47.7396
  longitude: -122.3426
  elevation: 129
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize:
    climate.thermostat_heating_1_9_1:      { friendly_name: Thermostat }
    climate.thermostat_cooling_1_9_2:      { hidden: true }
    climate.thermostat_heating_econ_9_11:  { hidden: true }
    climate.thermostat_cooling_econ_9_12:  { hidden: true }
    sensor.frontdoorlock_alarm_type_16_0:  { hidden: true }
    sensor.frontdoorlock_alarm_level_16_1: { hidden: true }
    sensor.backdoorlock_alarm_type_17_0:   { hidden: true }
    sensor.backdoorlock_alarm_level_17_1:  { hidden: true }

logger:
  default: info
  logs:
    homeassistant.core: warning
    homeassistant.components.sensor.command_line: warning
    custom_components: debug
    custom_components.bwio: info

group:
  outdoorlights:
    name: Outdoor Lights
    entities:
      - switch.drivewaylight_switch_12_0
      - switch.frontdoorlight_switch_3_0


http: !include http.yaml
automation: !include automation.yaml
alarm_control_panel: !include alarm.yaml
recorder: { purge_days: 14 }
frontend:
history:
logbook:
sun:


# ZWave setup
zwave:
  usb_path: /dev/zwave
  config_path: /home/pi/.homeassistant/ozwconfig
  polling_interval: 60000
  customize:
    sensor.thermostat_temperature_9_1: { polling_intensity: 1 }
    climate.thermostat_heating_1_9_1:  { polling_intensity: 1 }


# My custom zwave lock interface bits
usercode:
locklogger:
panel_custom:
  - name: locks
    sidebar_title: ZWave Locks
    sidebar_icon: mdi:lock
  - name: alarm
    sidebar_title: Alarm
    sidebar_icon: mdi:security-home
    config:
      alarmid: alarm_control_panel.house

# Generic sensors I like to keep an eye on for now
sensor:
  - platform: systemmonitor
    resources:
      - { type: memory_use_percent }
      - { type: processor_use }
  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'


# This is all of the I/O from my custom board
bwio:
  port: /dev/bwio

binary_sensor:
  - platform: bwio
    pins: 
       0:  [ littlewindow,     opening ]
       1:  [ diningwindow,     opening ]
       2:  [ pin2,             opening ] # unknown signal, always ok, where is it?
       3:  [ primarymotion,    motion  ]
       # 4: disconnected wire in the wall of the bedroom
       # 5: no input present
       # 6: no input present
       # 7: isn't connected, used as ground
       8:  [ livingroomwindow, opening ]
       9:  [ officewindow,     opening ]
       10: [ backdoor,         opening ]
       11: [ bedroomslider,    opening ]
       12: [ garagedoor,       opening ]
       13: [ patioslider,      opening ]
       14: [ frontdoor,        opening ]
       # 15 isn't connected, used as ground

switch:
  - platform: bwio
    pins: 
      11: garagedoorline
      15: alarm

# The garage door 'switch' needs to toggle on and off, do it here
script:
  garagedoor:
    sequence:
      - service: switch.turn_on
        data: { entity_id: switch.garagedoorline }
      - delay:
          milliseconds: 10
      - service: switch.turn_off
        data: { entity_id: switch.garagedoorline }


# Deal with bizzare reports from my ZWave Thermostat
shell_command:
  cleantemps: './cleantemps.py'

